<a href="https://colab.research.google.com/github/Kim-TaeKyoung/csv/blob/main/weather.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
########ASOS 시간 #########
from urllib.request import urlopen,Request
from urllib.parse import urlencode, unquote, quote_plus
import pandas as pd
from pandas import json_normalize
import json
from bs4 import BeautifulSoup
import urllib


url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList' #시간
#http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList  #일
my_key = 'vkLMC65StL1Jrc9%2B5R9tcbhKbcgFu72CiyqV6YbexXfV5iVmDKhObOt9Z8%2BdQYYTViR7yJsJJAjrrX9In8BIfg%3D%3D'
  
  # 날짜 범위의 최대값을 '20210906'로 설정
queryParams = '?' + urlencode({ 
    quote_plus('ServiceKey') : my_key, 
    quote_plus('pageNo') : '1', 
    quote_plus('numOfRows') : '999', 
    quote_plus('dataType') : 'JSON', 
    quote_plus('dataCd') : 'ASOS', 
    quote_plus('dateCd') : 'HR', 
    quote_plus('startDt') : '20210911' ,
    quote_plus('startHh') : '01', 
    quote_plus('endHh') : '01',
    quote_plus('endDt') : '20210912', 
    quote_plus('stnIds') : '108' })

request = urllib.request.Request(url + unquote(queryParams))
response_body = urlopen(request, timeout=60).read() # get bytes data
decode_data = response_body.decode('utf-8') # 바이트배열 문자화
#decode_data
json_file = json.loads(decode_data)
json_file
df = json_normalize(json_file['response']['body']['items']['item'])
df
#df.to_csv("weather.csv")
#li = ['tm','stnId','stnNm','ws','hm']#,'minTa','maxTa','avgTa','sumRn','maxWs','avgWs','ddMes']
#result = df.reindex(columns = li)
#result
################################################
#li = ['stnId','tm','avgTa','minTa','maxTa','sumRn','maxWs','avgWs','ddMes']
#data.loc[:,li]
################# string인 xml 파싱
# xml_parse = xmltodict.parse(decode_data)   
# xml_dict = json.loads(json.dumps(xml_parse))

# print(xml_dict['response']['body']['items']['item'][0]['maxTa'])
#################################################

# get_data = requests.get(url + unquote(queryParams))
# result_data = get_data.json()
# print(result_data['response']['body']['items']['item'][0]['maxTa'])
##############################################
# result = requests.get(url + queryParams)
# js = result.json()
# data = pd.DataFrame(js['response']['body']['items']['item'])

# response = urlopen(url + queryParams) 
# json_api = response.read().decode("utf-8")
# json_api
###############################################
# ##########json to json
# request = urllib.request.Request(url + unquote(queryParams))
# response_body = urlopen(request, timeout=60).read() # get bytes data
# decode_data = response_body.decode('utf-8')
# json_file = json.loads(decode_data)
###############################################
# ##########xml to json
# request = urllib.request.Request(url + unquote(queryParams))
# response_body = urlopen(request, timeout=60).read()
# result = xmltodict.parse(response_body)
# dictionary = json.loads(json.dumps(result)) #json
###########################################
# ##########xml에서 item만 뽑을떄 
# xmlobj = bs4.BeautifulSoup(response_body, 'lxml-xml')
# items = xmlobj.findAll('item') #xml item

                  tm rnum stnId stnNm    ta  ... tsQcflg m005Te m01Te m02Te m03Te
0   2021-09-11 01:00    1   108    서울  21.5  ...           24.4  24.2  24.5  24.6
1   2021-09-11 02:00    2   108    서울  21.1  ...           24.1  24.0  24.4  24.6
2   2021-09-11 03:00    3   108    서울  20.9  ...           23.9  23.7  24.2  24.5
3   2021-09-11 04:00    4   108    서울  20.7  ...           23.7  23.6  24.0  24.4
4   2021-09-11 05:00    5   108    서울  20.4  ...           23.6  23.4  23.9  24.3
5   2021-09-11 06:00    6   108    서울  20.1  ...           23.4  23.3  23.8  24.2
6   2021-09-11 07:00    7   108    서울  20.0  ...           23.3  23.1  23.6  24.2
7   2021-09-11 08:00    8   108    서울  21.2  ...           23.3  23.0  23.5  24.1
8   2021-09-11 09:00    9   108    서울  22.5  ...           23.5  23.1  23.4  24.0
9   2021-09-11 10:00   10   108    서울  23.4  ...           24.0  23.3  23.4  23.9
10  2021-09-11 11:00   11   108    서울  25.4  ...           24.6  23.7  23.4  23.9
11  2021-09-11 12:00   12   108    서울  25.9  ...           25.5  24.3  23.6  23.8
12  2021-09-11 13:00   13   108    서울  27.7  ...           26.2  24.8  23.8  23.9
13  2021-09-11 14:00   14   108    서울  28.8  ...           27.0  25.4  24.1  23.9
14  2021-09-11 15:00   15   108    서울  29.3  ...           27.6  26.0  24.4  24.0
15  2021-09-11 16:00   16   108    서울  29.0  ...           27.9  26.4  24.8  24.2
16  2021-09-11 17:00   17   108    서울  28.0  ...           27.7  26.6  25.2  24.4
17  2021-09-11 18:00   18   108    서울  27.1  ...           27.4  26.5  25.4  24.6
18  2021-09-11 19:00   19   108    서울  25.2  ...           26.9  26.3  25.5  24.8
19  2021-09-11 20:00   20   108    서울  24.5  ...           26.4  26.0  25.5  24.9
20  2021-09-11 21:00   21   108    서울  23.9  ...           26.0  25.7  25.4  25.0
21  2021-09-11 22:00   22   108    서울  23.1  ...           25.5  25.3  25.3  25.0
22  2021-09-11 23:00   23   108    서울  22.5  ...           25.2  25.0  25.1  25.0
23  2021-09-12 00:00   24   108    서울  22.0  ...           24.8  24.7  25.0  25.0
24  2021-09-12 01:00   25   108    서울  21.6  ...           24.5  24.4  24.8  24.9

[25 rows x 38 columns]

In [ ]:
######## ASOS 일 #########
from urllib.request import urlopen,Request
from urllib.parse import urlencode, unquote, quote_plus
import pandas as pd
from pandas import json_normalize
import json
from bs4 import BeautifulSoup
import urllib


#url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList' #시간
url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList'  #일
my_key = 'vkLMC65StL1Jrc9%2B5R9tcbhKbcgFu72CiyqV6YbexXfV5iVmDKhObOt9Z8%2BdQYYTViR7yJsJJAjrrX9In8BIfg%3D%3D'
  
  # 날짜 범위의 최대값을 '20210501'로 설정
queryParams = '?' + urlencode({ 
    quote_plus('ServiceKey') : my_key, 
    quote_plus('pageNo') : '5', 
    quote_plus('numOfRows') : '999', 
    quote_plus('dataType') : 'JSON', 
    quote_plus('dataCd') : 'ASOS', 
    quote_plus('dateCd') : 'DAY', #'HR'
    quote_plus('startDt') : '20210906' ,
    #quote_plus('startHh') : '01', 
    #quote_plus('endHh') : '01',
    quote_plus('endDt') : '20210908', 
    quote_plus('stnIds') : '108' })

request = urllib.request.Request(url + unquote(queryParams))
response_body = urlopen(request, timeout=60).read() # get bytes data
decode_data = response_body.decode('utf-8')
#decode_data
json_file = json.loads(decode_data)
#json_file
df = json_normalize(json_file['response']['body']['items']['item'])
df
li = ['tm','stnId'] #,'minTa','maxTa','avgTa','sumRn','maxWs','avgWs','ddMes']
result = df.reindex(columns = li)
result
#df[li].to_csv("weather.csv",index=False ) #csv 파일로저장

           tm stnId
0  2021-09-06   108
1  2021-09-07   108
2  2021-09-08   108

In [ ]:
################ 단기예보 조회################
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
from urllib.error import HTTPError

url = 'http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst'
service_key = 'vkLMC65StL1Jrc9%2B5R9tcbhKbcgFu72CiyqV6YbexXfV5iVmDKhObOt9Z8%2BdQYYTViR7yJsJJAjrrX9In8BIfg%3D%3D'
queryParams = '?' + urlencode({ quote_plus("serviceKey"): service_key, 
                              quote_plus("numOfRows"): '50',  
                              quote_plus("pageNo"): '3', # 페이지 번호 // default : 1 
                              quote_plus("dataType"): 'JSON', # 응답자료형식 : XML, JSON 
                              quote_plus("base_date"): '20210909', # 발표일자 // yyyymmdd 
                              quote_plus("base_time"): '0500', # 발표시각 // HHMM, 매 시각 40분 이후 호출 
                              quote_plus("nx"): '60', # 예보지점 X 좌표 
                              quote_plus("ny"): '127' # 예보지점 Y 좌표 
                               })

request = urllib.request.Request(url + unquote(queryParams))
response_body = urlopen(request, timeout=60).read() # get bytes data
decode_data = response_body.decode('utf-8')
#decode_data
json_file = json.loads(decode_data)
#json_file
df = json_normalize(json_file['response']['body']['items']['item'])
df

   baseDate baseTime category  nx   ny obsrValue
0  20210909     0500      PTY  60  127         0
1  20210909     0500      REH  60  127        94
2  20210909     0500      RN1  60  127         0
3  20210909     0500      T1H  60  127      19.5
4  20210909     0500      UUU  60  127      -0.9
5  20210909     0500      VEC  60  127        33
6  20210909     0500      VVV  60  127      -1.5
7  20210909     0500      WSD  60  127       1.9

In [ ]:
######## 서울시 교통량 지점 정보 #########
from urllib.request import urlopen,Request
from urllib.parse import urlencode, unquote, quote_plus
import pandas as pd
from pandas import json_normalize
import json
from bs4 import BeautifulSoup
import urllib

#url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList' #시간
#url = 'http://data.seoul.go.kr/dataList/OA-13314/A/1/datasetView.do'  #일
url = 'http://openapi.seoul.go.kr:8088/sample/xml/SpotInfo/1/5/'
my_key = '4b4169686c6b746b39335052794671'
  
  # 날짜 범위의 최대값을 '20210501'로 설정
queryParams = '?' + urlencode({ 
    quote_plus('KEY') : my_key, 
    quote_plus('TYPE') : 'xml', 
    quote_plus('SERVICE') : 'SEOUL_TRAFFIC', 
    quote_plus('START_INDEX') : '1', 
    quote_plus('END_INDEX') : '5', 
    # quote_plus('dateCd') : 'DAY', #'HR'
    # quote_plus('startDt') : '20210906' ,
    # #quote_plus('startHh') : '01', 
    # #quote_plus('endHh') : '01',
    # quote_plus('endDt') : '20210908', 
    # quote_plus('stnIds') : '108' 
    })


request = urllib.request.Request(url + unquote(queryParams))
response_body = urlopen(request, timeout=60).read()
result = xmltodict.parse(response_body)
dictionay = json.loads(json.dumps(result)) #json
#dictionay
df = json_normalize(dictionay['SpotInfo']['row'])
df

  spot_num       spot_nm      grs80tm_x      grs80tm_y
0     A-10    동호로(장충체육관)  200633.487975  451010.051429
1     B-06     화랑로(조선왕릉)         208764         459019
2     B-29     경인로(유한공고)  184313.594374  443266.257648
3     D-13      동일로(노원역)  205351.935482  461419.376043
4     D-36  사평대로(고속터미널역)  200691.392481  444896.469303